#ifndef BATTERY_CHECKER_H
#define BATTERY_CHECKER_H

#define TEMPERATURE_UPPER_LIMIT 45
#define TEMPERATURE_LOWER_LIMIT 0
#define SOC_UPPER_LIMIT 80
#define SOC_LOWER_LIMIT 20
#define CHARGE_RATE_UPPER_LIMIT 0.8
#define WARNING_TOLERANCE_PERCENTAGE 0.05
#define TEMPERATURE_WARNING_TOLERANCE (TEMPERATURE_UPPER_LIMIT * WARNING_TOLERANCE_PERCENTAGE)
#define SOC_WARNING_TOLERANCE (SOC_UPPER_LIMIT * WARNING_TOLERANCE_PERCENTAGE)
#define CHARGE_RATE_WARNING_TOLERANCE (CHARGE_RATE_UPPER_LIMIT * WARNING_TOLERANCE_PERCENTAGE)

int TemperatureIsOk(float temperature);
int SocIsOk(float soc);
 int ChargeRateIsOk(float chargeRate);
 int BatteryIsOk(float temperature, float soc, float chargeRate);

#endif // BATTERY_CHECKER_H
